### ISSUE TITLE
Incorrect font in "Ferelden After the Blight"

### ISSUE THREAD

**Issue by DanSoulman** [waterleemon/DAI-Codex#1]
In the codex for Ferelden after the Blight . The text in the 4th Paragraph "If Anora is Queen and the Warden is prince consort" is in the text typically used for regular text as opposed to the yellow font used typically.

**Comment by DanSoulman** [comment]
https://github.com/leechuyem/DAI-Codex/blob/master/assets/codex/places/ferelden_after_the_blight.md
My assumption is that you just need to add the \<h3> \</h3> at line 7.

**Comment by spaaacey** [comment]
Oh nice catch, and yep you're exactly right! i'll fix that by the next release coming next tuesday (17/12/2019)

**Comment by spaaacey** [comment]
The typo has been fixed in the new [release v1.0](https://github.com/leechuyem/DAI-Codex/releases/tag/v1.0) :)
